spring:

  datasource:
    url: jdbc:mysql://localhost:3306/****
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: '****'
    password: '****'

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
    database: mysql

logging:
  level:
    root: info
